django/level-four/tempProject/tempApp/urls.py
# Here is where we set the realtive url path
from django.urls import re_path as url
from tempApp import views


# TEMPLATE TAGGING
app_name = 'tempApp'

urlpatterns = [
    url(r'^relative/$',views.relative, name='relative'),
    url(r'^other/$',views.other, name='other')
]

django/level-four/tempProject/tempProject/urls.py
from django.contrib import admin
from django.urls import include, re_path as path
from tempApp import views

urlpatterns = [
    path(r'^$',views.index, name='index'),
    path(r'^admin/', admin.site.urls),
    path(r'^tempApp/',include('tempApp.urls')),
]

django/level-four/tempProject/tempApp/models.py
from django.db import models

# Create your models here.

django/level-four/tempProject/tempApp/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# 


# def index(request):
#     return HttpResponse('Hello World')

def index(request):
    return render(request,'tempApp/index.html')

def other(request):
    return render(request,'tempApp/other.html')

def relative(request):
    return render(request,'tempApp/relative_url_templates.html')

django/level-four/tempProject/templates/tempApp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Index</h1>
            <p>
                <a href="{% url 'tempApp:other' %}">
                    <button class="btn btn-primary">
                        OTHER PAGE
                    </button>
                </a>
            </p>
            <p>
                <a href="{% url 'tempApp:relative' %}">
                    <button class="btn btn-info">
                        RELATIVE PAGE
                    </button>
                </a>
            </p>
        </div>
    </div>
</body>

</html>

django/level-four/tempProject/templates/tempApp/other.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Other Page</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Other</h1>
            <a href="{% url 'tempApp:relative' %}">
                <button class="btn btn-info">
                    RELATIVE PAGE
                </button>
            </a>
        </div>
    </div>
</body>

</html>

django/level-four/tempProject/templates/tempApp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Relative Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome to Relative URL Templates</h1>
            <p>
                <a href="{% url 'tempApp:other' %}">
                    <button class="btn btn-primary">
                        OTHER PAGE
                    </button>
                </a>
            </p>
            <p>
                <a href="{% url 'admin:index' %}">
                    <button class="btn btn-info">
                        ADMIN PAGE
                    </button>
                </a>
            </p>

            <p>
                <a href="{% url 'index' %}">
                    <button class="btn btn-warning">
                        HOME
                    </button>
                </a>
            </p>
        </div>
    </div>
</body>

</html>