django/level-five/learning_users/basic_app/urls.py
from django.urls import re_path as url
from basic_app import views

# TEMPLATE URLS
app_name = 'basic_app'


urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='login')
]

django/level-five/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import include, re_path as url
from basic_app import views

urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/',views.special,name='special')

]

django/level-five/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # add additional attributes
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    portofolio_site = models.URLField(blank=True)
    
    def __str__(self):
        return self.user.username

django/level-five/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ['username', 'email', 'password']


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portofolio_site', 'profile_pic')

django/level-five/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
# import needed that will assint with creating the login view
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

#example of how decorators can be use
@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request): 
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            # save user in the database
            user = user_form.save()
            # hashing the password provided by the user
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            # This will set the one to one relationship
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            # once we save user and image
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # function that will authenticate user
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request=request,user=user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('Someone tried to login and failed!')
            print('Username: {} and password {}.'.format(username, password))
            return HttpResponse('Invalid Login Details supplied')
    else:
        return render(request,'basic_app/login.html',{})

django/level-five/learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">Home</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'basic_app:register' %}" class="navbar-link">Register</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="navbar-link">Logout</a></li>
                {% else %}
                <li><a href="{% url 'basic_app:login' %}" class="navbar-link">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block body_block %}
    <div class="container">

    </div>
    {% endblock %}
</body>

</html>

django/level-five/learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>
{% endblock %}

django/level-five/learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" class="btn btn-info" value="Login">
    </form>
</div>
{% endblock %}

django/level-five/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registrering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form</h3>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token%}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}