django/cbv/clone_project/clone_project/urls.py
from django.contrib import admin
from django.urls import include, re_path as url
from temp_app import views



urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^temp_app/',include('temp_app.urls', namespace='temp_app'))

    # returning a base class view
    # url(r'^$', views.CBView.as_view())
    # url(r'^$', views.index, name='home')
]

django/cbv/clone_project/temp_app/urls.py
from django.urls import re_path as url
from temp_app import views

app_name = 'temp_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create_school/$',views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(), name='delete'),
    url(r'create_student', views.StudentCreateView.as_view(),name='create_student'),
]

django/cbv/clone_project/temp_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('temp_app:detail',kwargs={'pk':self.pk})
        
    
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School,related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('temp_app:detail', kwargs={'pk': self.pk})

django/cbv/clone_project/temp_app/views.py
from typing import Any
from django.shortcuts import render
from . import models
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django import forms
# from django.http import HttpResponse


# Create your views here.

# def index(request):
#     return render(request, 'index.html')

# turning a view into a class page
# class CBView(View):
#     def get(self, request):
#         return HttpResponse('CLASS BASED VIEW!')

class IndexView(TemplateView):
    template_name = 'index.html'

    # def get_context_data(self, **kwargs: Any):
    #     context = super().get_context_data(**kwargs)
    #     context['injectme'] = 'BASIC INJECTION'
    #     return context

# how to use context dictionary
# This will provide a list of all the record
class SchoolListView(ListView):
    # return a list of school_list
    # we can use this variable to change the list 
    model = models.School
    context_object_name = 'schools'

# this will provide all the detail in a view
class SchoolDetailView(DetailView):
    model = models.School
    template_name = 'temp_app/school_detail.html'
    context_object_name = 'school_detail'

# create a class that will help with creating view
class SchoolCreateView(CreateView):
    fields = ('name','principal', 'location')
    model = models.School

# create class to update view
class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

# create class to delete view
class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("temp_app:list")

# add student
class StudentCreateView(CreateView):
    fields = ('name','age', 'School')
    model = models.Student
    # form_class = StudentForm
    template_name = 'temp_app/create_student.html'
    success_url = reverse_lazy("temp_app:list")

    

    

django/cbv/clone_project/temp_app/templates/temp_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}" class="navbar-brand">Home</a></li>
            <li><a href="{% url 'temp_app:list' %}" class="navbar-link">School</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
            <li><a href="#" class="navbar-link"></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>

django/cbv/clone_project/temp_app/templates/temp_app/create_student.html
{% extends "temp_app/basic_app_base.html" %}

{% block body_block %}
<div class="containter">
    <div class="jumbotron">
        <h1>Create Student</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

django/cbv/clone_project/temp_app/templates/temp_app/school_confirm_delete.html
{% extends "temp_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>Delete {{school.name}}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'temp_app:detail' pk=school.pk %}">Cancel</a>
    </form>
</div>
{% endblock %}

django/cbv/clone_project/temp_app/templates/temp_app/school_detail.html
{% extends "temp_app/basic_app_base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to the School Detail</h1>
    <h2>School Detail</h2>
    <p>
        Name: {{school_detail.name}}
    </p>
    <p>
        Principle: {{school_detail.principal}}
    </p>
    <p>
        Location: {{school_detail.location}}
    </p>
    <h3>Student:</h3>
    {% if school_detail.students.all.count > 0 %}
    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
    {% else %}
    <p>No students are attend this school.</p>
    {% endif %}
</div>

<div class="container">
    <p><a class="btn btn-warning" href="{% url 'temp_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

django/cbv/clone_project/temp_app/templates/temp_app/school_form.html
{% extends "temp_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>School Form</h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif%}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

</div>
{% endblock %}

django/cbv/clone_project/temp_app/templates/temp_app/school_list.html
{% extends "temp_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to A list of all the School!</h1>
    <ol>
        {% for school in schools %}
        <h2>
            <li><a href="{{school.id}}">{{school.name}}</a></li>
        </h2>
        {% endfor %}
    </ol>
</div>

<!-- Create a link that will direct to the next -->
<a href="{% url 'temp_app:create' %}">
    <input type="submit" value="Add School" class="btn btn-info">
</a>
<a href="{% url 'temp_app:create_student' %}">
    <input type="submit" value="Add Student" class="btn btn-success">
</a>

{% endblock %}

django/cbv/clone_project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}" class="navbar-brand">Home</a></li>
            <li><a href="{% url 'temp_app:list' %}" class="navbar-link">School</a></li>
            <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
            <li><a href="#" class="navbar-link"></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>

django/cbv/clone_project/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>HOME PAGE</h1>
</div>
{% endblock %}